export const rolesAccessLevelMap = new Map<string, string>();
rolesAccessLevelMap.set('employeeAccessLevel', "Users");
rolesAccessLevelMap.set('rolesAccessLevel', "Roles");
rolesAccessLevelMap.set('cardAccessLevel', "Card");
rolesAccessLevelMap.set('brandAccessLevel', "Brand");
rolesAccessLevelMap.set('userOrdersAccessLevel', "User orders");
rolesAccessLevelMap.set('bulkOrdersAccessLevel', "Bulk orders");
rolesAccessLevelMap.set('partnersOrdersAccessLevel', "Partners orders");
rolesAccessLevelMap.set('userVendorsAccessLevel', "User Vendors");
rolesAccessLevelMap.set('bulkSalesVendorsAccessLevel', "Bulk Sales Vendors");
rolesAccessLevelMap.set('partnersSalesVendorsAccessLevel', "Partners Sales Vendors");
rolesAccessLevelMap.set('transactionsAccessLevel', "Transactions");
rolesAccessLevelMap.set('tasksAccessLevel', "Tasks");
rolesAccessLevelMap.set('settingsAccessLevel', "Settings");
rolesAccessLevelMap.set('analyticsAccessLevel', "Analytics");
rolesAccessLevelMap.set('auditAccessLevel', "Audit");
