export const accessLevels = [
  "cardAccessLevel",
  "brandAccessLevel",
  "employeeAccessLevel",
  "rolesAccessLevel",
  "userOrdersAccessLevel",
  "bulkOrdersAccessLevel",
  "partnersOrdersAccessLevel",
  "userVendorsAccessLevel",
  "bulkSalesVendorsAccessLevel",
  "partnersSalesVendorsAccessLevel",
  "transactionsAccessLevel",
  "tasksAccessLevel",
  "settingsAccessLevel",
  "analyticsAccessLevel",
  "auditAccessLevel",
];
