export enum SellCardStatus {
    Undefined = "Undefined",
    Reserved = "Reserved",
    Loaded = "Loaded",
    OnSale = "OnSale",
    PendingSaleCheck = "PendingSaleCheck",
    PendingCheck = "PendingCheck",
    Checked = "Checked",
    PreListed = "PreListed",
    Active = "Active",
    Rejected = "Rejected",
    Used = "Used",
    PartiallyUsed = "PartiallyUsed",
    GuaranteeExpired = "GuaranteeExpired",
    Investigation = "Investigation",
    Denied = "Denied",
    Inactive = "Inactive",
    Send = "Send",
    Debt = "Debt",
    Hold = "Hold",
    Cancelled = "Cancelled"
}